Repository jeremy0405/issue-tracker, pull requests merged in 2022-06, with the labels that each got.

#10 [FE] 개발 환경 다시 세팅
  fe/.eslintrc.js
  fe/.gitignore
  fe/.prettierrc
  fe/.storybook/main.js
  fe/.storybook/preview.js
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.tsx
  fe/src/index.tsx
  fe/src/stories/Button.stories.tsx
  fe/src/stories/Button.tsx
  fe/src/stories/Header.stories.tsx
  fe/src/stories/Header.tsx
  fe/src/stories/Introduction.stories.mdx
  fe/src/stories/Page.stories.tsx
  fe/src/stories/Page.tsx
  fe/src/stories/assets/code-brackets.svg
  fe/src/stories/assets/colors.svg
  fe/src/stories/assets/comments.svg
  fe/src/stories/assets/direction.svg
  fe/src/stories/assets/flow.svg
  fe/src/stories/assets/plugin.svg
  fe/src/stories/assets/repo.svg
  fe/src/stories/assets/stackalt.svg
  fe/src/stories/button.css
  fe/src/stories/header.css
  fe/src/stories/page.css
  fe/tsconfig.json
Labels: 🖥 FE, Setting

#9 [BE] - spring boot 초기환경 세팅
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/team29/hoorry/issuetracker/IssueTrackerApplication.java
  BE/src/main/resources/application.yml
  BE/src/test/java/team29/hoorry/issuetracker/IssueTrackerApplicationTests.java
Labels: ⚙️ BE, Setting

#12 [FE] 💄 themeProvider 적용 및 Button / Input 컴포넌트 구현
  fe/.eslintrc.js
  fe/.storybook/preview.js
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.tsx
  fe/src/assets/icons/Property 1=UserImageLarge.svg
  fe/src/assets/icons/alertCircle.svg
  fe/src/assets/icons/archive.svg
  fe/src/assets/icons/calendar.svg
  fe/src/assets/icons/checkBoxActive.svg
  fe/src/assets/icons/checkBoxDisable.svg
  fe/src/assets/icons/checkBoxInitial.svg
  fe/src/assets/icons/checkOffCircle.svg
  fe/src/assets/icons/checkOnCircle.svg
  fe/src/assets/icons/edit.svg
  fe/src/assets/icons/milestone.svg
  fe/src/assets/icons/paperclip.svg
  fe/src/assets/icons/plus.svg
  fe/src/assets/icons/refresh-ccw.svg
  fe/src/assets/icons/search.svg
  fe/src/assets/icons/smile.svg
  fe/src/assets/icons/tag.svg
  fe/src/assets/icons/trash.svg
  fe/src/assets/icons/xSquare.svg
  fe/src/assets/logo/LogotypeLarge.svg
  fe/src/assets/logo/LogotypeMedium.svg
  fe/src/assets/userImg/userImageLarge.svg
  fe/src/assets/userImg/userImageSmall.svg
  fe/src/components/Button/Button.stories.tsx
  fe/src/components/Button/index.styles.ts
  fe/src/components/Button/index.tsx
  fe/src/components/Input/Input.stories.tsx
  fe/src/components/Input/index.styles.ts
  fe/src/components/Input/index.tsx
  fe/src/custom.d.ts
  fe/src/index.tsx
  fe/src/stories/Button.stories.tsx
  fe/src/stories/Button.tsx
  fe/src/stories/Header.stories.tsx
  fe/src/stories/Header.tsx
  fe/src/stories/Introduction.stories.mdx
  fe/src/stories/Page.stories.tsx
  fe/src/stories/Page.tsx
  fe/src/stories/assets/code-brackets.svg
  fe/src/stories/assets/colors.svg
  fe/src/stories/assets/comments.svg
  fe/src/stories/assets/direction.svg
  fe/src/stories/assets/flow.svg
  fe/src/stories/assets/plugin.svg
  fe/src/stories/assets/repo.svg
  fe/src/stories/assets/stackalt.svg
  fe/src/stories/button.css
  fe/src/stories/header.css
  fe/src/stories/page.css
  fe/src/styles/globalStyle.ts
  fe/src/styles/theme.ts
Labels: 🖥 FE, UI

#16 [Be] - 더미데이터 추가
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/data.sql
  BE/src/main/resources/db/schema.sql
Labels: ⚙️ BE

#17 [FE] ✨ 각 페이지에 대한 라우터 생성
  fe/.eslintrc.js
  fe/src/App.tsx
  fe/src/Router/index.tsx
  fe/src/pages/AddIssue.tsx
  fe/src/pages/Home.tsx
  fe/src/pages/IssueDetail.tsx
  fe/src/pages/IssueList.tsx
  fe/src/pages/LableList.tsx
  fe/src/pages/Login.tsx
  fe/src/pages/MilestoneList.tsx
  fe/src/pages/NotFound.tsx
Labels: feature, 🖥 FE, Router

#22 Fix styled component attrs bug
  fe/src/components/Atoms/Button/index.tsx
  fe/src/components/Atoms/Input/index.styles.ts
  fe/src/components/Atoms/Input/index.tsx
  fe/src/components/Molecules/LoginForm/index.tsx
  fe/src/components/Organisms/LoginAndRegister/index.tsx
Labels: bug, 🖥 FE

#28 [FE] PR 1주차 첫번째 리뷰 반영하기
  fe/src/components/Atoms/Button/index.styles.ts
  fe/src/components/Atoms/Button/index.tsx
  fe/src/components/Atoms/Input/Input.stories.tsx
  fe/src/components/Atoms/Input/index.styles.ts
  fe/src/components/Atoms/Input/index.tsx
Labels: 🖥 FE, Fix

#29 [FE] UI - FilterBar, AddIssueForm 컴포넌트
  fe/src/assets/icons/Property 1=UserImageLarge.svg
  fe/src/assets/icons/caret.svg
  fe/src/components/Atoms/Dropdown/Dropdown.stories.tsx
  fe/src/components/Atoms/Dropdown/DropdownIndicators/DropdownIndicators.stories.tsx
  fe/src/components/Atoms/Dropdown/DropdownIndicators/DropdownIndicators.styles.ts
  fe/src/components/Atoms/Dropdown/DropdownIndicators/index.tsx
  fe/src/components/Atoms/Dropdown/DropdownPanels/DropdownPanels.stories.tsx
  fe/src/components/Atoms/Dropdown/DropdownPanels/index.styles.ts
  fe/src/components/Atoms/Dropdown/DropdownPanels/index.tsx
  fe/src/components/Atoms/Dropdown/index.styles.ts
  fe/src/components/Atoms/Dropdown/index.tsx
  fe/src/components/Atoms/Input/Input.stories.tsx
  fe/src/components/Atoms/Input/index.styles.ts
  fe/src/components/Atoms/Input/index.tsx
  fe/src/components/Atoms/Textarea/Textarea.stories.tsx
  fe/src/components/Atoms/Textarea/index.styles.ts
  fe/src/components/Atoms/Textarea/index.tsx
  fe/src/components/Molecules/AddIssueForm/AddIssueForm.stories.tsx
  fe/src/components/Molecules/AddIssueForm/index.styles.ts
  fe/src/components/Molecules/AddIssueForm/index.tsx
  fe/src/components/Molecules/FilterBar/FilterBar.stories.tsx
  fe/src/components/Molecules/FilterBar/index.tsx
  fe/src/components/Molecules/LoginForm/index.tsx
  fe/src/styles/theme.ts
Labels: 🖥 FE, UI

#31 [Fe] 머지한 코드 리팩토링
  fe/src/components/Atoms/Button/Button.stories.tsx
  fe/src/components/Atoms/Button/index.styles.ts
  fe/src/components/Atoms/Button/index.tsx
  fe/src/components/Atoms/Dropdown/Dropdown.stories.tsx
  fe/src/components/Atoms/Dropdown/DropdownIndicators/DropdownIndicators.stories.tsx
  fe/src/components/Atoms/Dropdown/DropdownIndicators/DropdownIndicators.styles.ts
  fe/src/components/Atoms/Dropdown/DropdownIndicators/index.tsx
  fe/src/components/Atoms/Dropdown/DropdownPanels/DropdownPanels.stories.tsx
  fe/src/components/Atoms/Dropdown/DropdownPanels/index.styles.ts
  fe/src/components/Atoms/Dropdown/DropdownPanels/index.tsx
  fe/src/components/Atoms/Dropdown/index.tsx
  fe/src/components/Atoms/Icon/svgs.tsx
  fe/src/components/Atoms/Input/Input.stories.tsx
  fe/src/components/Atoms/Input/index.tsx
  fe/src/components/Atoms/Issue/Issue.stories.tsx
  fe/src/components/Atoms/Label/Label.stories.tsx
  fe/src/components/Atoms/Label/index.tsx
  fe/src/components/Atoms/Tab/Tab.stories.tsx
  fe/src/components/Atoms/Tab/index.styled.ts
  fe/src/components/Atoms/Tab/index.tsx
  fe/src/components/Atoms/Textarea/Textarea.stories.tsx
  fe/src/components/Atoms/Textarea/index.styles.ts
  fe/src/components/Atoms/Textarea/index.tsx
  fe/src/components/Molecules/FilterBar/FilterBar.stories.tsx
  fe/src/components/Molecules/FilterBar/index.tsx
  fe/src/components/Molecules/IssueList/IssueItem/IssueItem.stories.tsx
  fe/src/components/Molecules/LoginForm/index.tsx
  fe/src/components/Molecules/Tabs/Tabs.stories.tsx
Labels: 🖥 FE, Fix

#34 [BE] - 회원가입 기능 구현
  BE/build.gradle
  BE/src/main/java/team29/hoorry/issuetracker/IssueTrackerApplication.java
  BE/src/main/java/team29/hoorry/issuetracker/core/auth/AuthController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/auth/AuthService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/auth/dto/AuthMemberResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/auth/dto/AuthResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/auth/dto/AuthToken.java
  BE/src/main/java/team29/hoorry/issuetracker/core/auth/dto/AuthTokenRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/common/BaseTimeEntity.java
  BE/src/main/java/team29/hoorry/issuetracker/core/common/embeddable/DateTimeTracker.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueMockService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/Comment.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/Issue.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/IssueLabel.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueFilter.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueStatusUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueTitleUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssueUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssuesStatusUpdateRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/CommentResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueDetailResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueLabelResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueMemberResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueMilestoneResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueMilestoneSimpleResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssuesResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/ReactionResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/AccessToken.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/JwtConst.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/JwtGenerator.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/RefreshToken.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/dto/JwtResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/MemberController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/MemberRepository.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/MemberService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/domain/Member.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/dto/MemberRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/MilestoneMockService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/domain/Milestone.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/dto/MilestoneAddRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/dto/MilestoneDetailResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/milestone/dto/MilestonesResponse.java
Labels: ⚙️ BE, feature

#37 [FE] IssueList 컴포넌트 구현
  fe/src/components/Atoms/CheckBox/CheckBox.stories.tsx
  fe/src/components/Atoms/CheckBox/index.styles.ts
  fe/src/components/Atoms/CheckBox/index.tsx
  fe/src/components/Atoms/Issue/Issue.stories.tsx
  fe/src/components/Atoms/Issue/Issue.styles.tsx
  fe/src/components/Atoms/Issue/index.tsx
  fe/src/components/Atoms/Label/Label.stories.tsx
  fe/src/components/Atoms/Label/index.styles.tsx
  fe/src/components/Atoms/Label/index.tsx
  fe/src/components/Atoms/Tab/index.styled.ts
  fe/src/components/Atoms/UserImage/UserImage.stories.tsx
  fe/src/components/Atoms/UserImage/UserImage.styles.tsx
  fe/src/components/Atoms/UserImage/index.tsx
  fe/src/components/Molecules/IssueList/IssueItem/IssueItem.stories.tsx
  fe/src/components/Molecules/IssueList/IssueItem/index.styles.tsx
  fe/src/components/Molecules/IssueList/IssueItem/index.tsx
  fe/src/components/Molecules/IssueList/index.styles.tsx
  fe/src/components/Molecules/IssueList/index.tsx
  fe/src/components/Molecules/IssueList/issueList.stories.tsx
  fe/src/components/Molecules/Tabs/index.tsx
  fe/src/components/Organisms/Header/index.tsx
Labels: 🖥 FE, UI

#38 [FE] SideBar 컴포넌트 구현, Molecules 상태 연동
  fe/src/assets/icons/caret.svg
  fe/src/assets/icons/smallLabel.svg
  fe/src/components/Atoms/Dropdown/Dropdown.stories.tsx
  fe/src/components/Atoms/Dropdown/DropdownIndicators/DropdownIndicators.stories.tsx
  fe/src/components/Atoms/Dropdown/DropdownIndicators/DropdownIndicators.styles.ts
  fe/src/components/Atoms/Dropdown/DropdownIndicators/index.styles.ts
  fe/src/components/Atoms/Dropdown/DropdownIndicators/index.tsx
  fe/src/components/Atoms/Dropdown/DropdownPanels/DropdownPanels.stories.tsx
  fe/src/components/Atoms/Dropdown/DropdownPanels/index.styles.ts
  fe/src/components/Atoms/Dropdown/DropdownPanels/index.tsx
  fe/src/components/Atoms/Dropdown/index.styles.ts
  fe/src/components/Atoms/Dropdown/index.tsx
  fe/src/components/Atoms/Icon/svgs.tsx
  fe/src/components/Atoms/Input/index.styles.ts
  fe/src/components/Atoms/Input/index.tsx
  fe/src/components/Atoms/Milestone/Milestone.stories.tsx
  fe/src/components/Atoms/Milestone/index.styles.ts
  fe/src/components/Atoms/Milestone/index.tsx
  fe/src/components/Atoms/SmallLabel/SmallLabel.stories.tsx
  fe/src/components/Atoms/SmallLabel/index.tsx
  fe/src/components/Molecules/AddIssueForm/index.tsx
  fe/src/components/Molecules/FilterBar/FilterBar.stories.tsx
  fe/src/components/Molecules/FilterBar/index.tsx
  fe/src/components/Molecules/LoginForm/index.tsx
  fe/src/components/Molecules/SideBar/SideBar.stories.tsx
  fe/src/components/Molecules/SideBar/index.styles.ts
  fe/src/components/Molecules/SideBar/index.tsx
  fe/src/hooks/useInput.tsx
  fe/src/styles/theme.ts
Labels: feature, 🖥 FE, UI

#39 [BE] - 로그인 기능 구현
  BE/src/main/java/team29/hoorry/issuetracker/config/WebMvcConfig.java
  BE/src/main/java/team29/hoorry/issuetracker/core/auth/AuthService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/exception/AuthException.java
  BE/src/main/java/team29/hoorry/issuetracker/core/exception/EmptyTokenException.java
  BE/src/main/java/team29/hoorry/issuetracker/core/exception/ExceptionMessage.java
  BE/src/main/java/team29/hoorry/issuetracker/core/exception/GlobalExceptionHandler.java
  BE/src/main/java/team29/hoorry/issuetracker/core/exception/InvalidTokenException.java
  BE/src/main/java/team29/hoorry/issuetracker/core/exception/dto/ErrorResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/interceptor/UserValidateInterceptor.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/JwtConst.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/JwtParser.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/JwtRepository.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/JwtValidator.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/RefreshToken.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/dto/JwtResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/MemberController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/MemberService.java
Labels: ⚙️ BE, feature

#48 [FE] 로그인 기능 구현
  fe/src/Router/index.tsx
  fe/src/components/Atoms/Dropdown/DropdownPanels/index.tsx
  fe/src/components/Atoms/Milestone/Milestone.stories.tsx
  fe/src/components/Atoms/Milestone/index.styles.ts
  fe/src/components/Atoms/Milestone/index.tsx
  fe/src/components/Molecules/AddIssueForm/index.tsx
  fe/src/components/Molecules/FilterBar/index.tsx
  fe/src/components/Molecules/IssueList/index.tsx
  fe/src/components/Molecules/LoginForm/index.tsx
  fe/src/components/Molecules/SideBar/SideBar.stories.tsx
  fe/src/components/Molecules/SideBar/index.tsx
  fe/src/components/Organisms/Header/index.tsx
  fe/src/components/Organisms/LoginAndRegister/index.tsx
  fe/src/components/Organisms/SignUpForm/index.tsx
  fe/src/components/types.ts
  fe/src/helpers/constants/openCloseFilter.ts
  fe/src/helpers/utils/fetchData.ts
  fe/src/hooks/useInput.tsx
  fe/src/pages/AddIssue.tsx
  fe/src/pages/Issues.tsx
  fe/src/pages/Login/Oauth.tsx
  fe/src/pages/Login/SignUp.tsx
  fe/src/pages/Login/index.tsx
Labels: 🖥 FE, Fix

#50 [BE] - 파일 S3 업로드 기능 구현
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/team29/hoorry/issuetracker/core/common/fileupload/FileUploadController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/common/fileupload/FileUploadResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/common/fileupload/FileUploadService.java
  BE/src/main/resources/application.yml
Labels: ⚙️ BE, feature

#62 [BE] - 라벨 도메인 기능 구현
  BE/build.gradle
  BE/src/main/java/team29/hoorry/issuetracker/core/exception/GlobalExceptionHandler.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/LabelController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/LabelMockService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/LabelService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/domain/Label.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/dto/LabelAddRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/dto/LabelsResponse.java
Labels: ⚙️ BE, feature

#61 [BE] - 멤버 로그인 기능 구현
  BE/src/main/java/team29/hoorry/issuetracker/core/member/MemberController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/MemberRepository.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/MemberService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/dto/MemberAndJwtResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/dto/MemberLoginRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/dto/MemberRequest.java
Labels: ⚙️ BE, feature

#63 [FE] Issue Detail 페이지 UI 구현
  fe/src/components/Atoms/Input/index.tsx
  fe/src/components/Atoms/Label/index.styles.tsx
  fe/src/components/Atoms/Label/index.tsx
  fe/src/components/Atoms/Textarea/index.tsx
  fe/src/components/Molecules/AddIssueForm/index.tsx
  fe/src/components/Molecules/Comment/Comment.stories.tsx
  fe/src/components/Molecules/Comment/index.styles.ts
  fe/src/components/Molecules/Comment/index.tsx
  fe/src/components/Molecules/FilterBar/index.tsx
  fe/src/components/Molecules/IssueHeader/IssueHeader.stories.tsx
  fe/src/components/Molecules/IssueHeader/index.styles.ts
  fe/src/components/Molecules/IssueHeader/index.tsx
  fe/src/components/Molecules/LoginForm/index.tsx
  fe/src/components/Organisms/SignUpForm/index.tsx
  fe/src/components/types.ts
  fe/src/pages/AddIssue.tsx
  fe/src/pages/IssueDetail.tsx
  fe/src/pages/Issues.tsx
Labels: feature, 🖥 FE, UI

#65 [BE] - 이슈 상세 조회 API 기능 구현
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueCustomRepository.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueMockService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueRepository.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueRepositoryImpl.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/Comment.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/CommentReaction.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/Issue.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/CommentResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/IssueDetailResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/response/ReactionResponse.java
  BE/src/main/java/team29/hoorry/issuetracker/core/label/domain/Label.java
  BE/src/main/resources/db/data.sql
Labels: ⚙️ BE, feature

#69 [BE] - 이슈 도메인 - 코멘트 API 구현
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/CommentReactionRepository.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/CommentRepository.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/CommentService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/Comment.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/CommentReaction.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/Reaction.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/CommentSaveRequest.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/ReactionSaveRequest.java
Labels: ⚙️ BE, feature

#72 [BE] - 이슈 등록 API 구현
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/CommentService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueController.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueMockService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/IssueService.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/Issue.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/IssueAssignee.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/domain/IssueLabel.java
  BE/src/main/java/team29/hoorry/issuetracker/core/issue/dto/request/IssuesSaveRequest.java
Labels: ⚙️ BE, feature

#74 [BE] - refresh token 저장용 redis 연동
  BE/build.gradle
  BE/src/main/java/team29/hoorry/issuetracker/config/RedisConfig.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/JwtConst.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/JwtGenerator.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/JwtParser.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/JwtRedisRepository.java
  BE/src/main/java/team29/hoorry/issuetracker/core/jwt/RefreshToken.java
  BE/src/main/java/team29/hoorry/issuetracker/core/member/MemberService.java
  BE/src/main/resources/application.yml
Labels: ⚙️ BE, feature

#76 [FE] Label 수정, 새로운 이슈 등록
  fe/.eslintrc.js
  fe/package-lock.json
  fe/package.json
  fe/src/Router/index.tsx
  fe/src/Router/private.tsx
  fe/src/Router/public.tsx
  fe/src/api/issue.ts
  fe/src/api/label.ts
  fe/src/components/Atoms/Button/index.styles.ts
  fe/src/components/Atoms/ColorCode/index.tsx
  fe/src/components/Atoms/Dropdown/DropdownIndicators/index.styles.ts
  fe/src/components/Atoms/Dropdown/index.styles.ts
  fe/src/components/Atoms/Input/index.styles.ts
  fe/src/components/Atoms/Input/index.tsx
  fe/src/components/Atoms/Label/index.styles.tsx
  fe/src/components/Atoms/Tab/index.styled.ts
  fe/src/components/Atoms/Textarea/index.styles.ts
  fe/src/components/Atoms/Textarea/index.tsx
  fe/src/components/Molecules/AddIssueForm/index.styles.ts
  fe/src/components/Molecules/AddIssueForm/index.tsx
  fe/src/components/Molecules/Comment/index.styles.ts
  fe/src/components/Molecules/Comment/index.tsx
  fe/src/components/Molecules/CommonForm/Label/LabelForm/index.tsx
  fe/src/components/Molecules/FilterBar/index.tsx
  fe/src/components/Molecules/IssueHeader/index.tsx
  fe/src/components/Molecules/LabelList/LabelItem/index.tsx
  fe/src/components/Molecules/LabelList/index.tsx
  fe/src/components/Molecules/LoginForm/index.tsx
  fe/src/components/Molecules/SideBar/index.tsx
  fe/src/components/Organisms/Header/Header.stories.tsx
  fe/src/components/Organisms/Header/index.tsx
  fe/src/components/Organisms/LabelForm/LabelInput/index.tsx
  fe/src/components/Organisms/LabelForm/index.styles.ts
  fe/src/components/Organisms/LabelForm/index.tsx
  fe/src/components/Organisms/SignUpForm/index.tsx
  fe/src/helpers/utils/fetchData.ts
  fe/src/hooks/useInput.tsx
  fe/src/pages/AddIssue.tsx
  fe/src/pages/Home.tsx
  fe/src/pages/IssueDetail.tsx
  fe/src/pages/Issues.tsx
  fe/src/pages/LableList.tsx
  fe/src/pages/Login/Oauth.tsx
  fe/src/pages/Login/SignUp.tsx
  fe/src/pages/index.tsx
  fe/src/styles/globalStyle.ts
  fe/src/styles/markdown.ts
Labels: feature, 🖥 FE

#78 [FE] 이슈 페이지에 페이징 적용 및 기타 수정 사항
  fe/src/api/issue.ts
  fe/src/api/label.ts
  fe/src/api/member.ts
  fe/src/api/milestone.ts
  fe/src/components/Atoms/Button/index.styles.ts
  fe/src/components/Atoms/Dropdown/DropdownPanels/index.tsx
  fe/src/components/Molecules/CommonList/index.tsx
  fe/src/components/Molecules/Pagination/index.styles.ts
  fe/src/components/Molecules/Pagination/index.tsx
  fe/src/components/types.ts
  fe/src/pages/AddIssue.tsx
  fe/src/pages/IssueDetail.tsx
  fe/src/pages/Issues.tsx
  fe/src/pages/LableList.tsx
Labels: feature, 🖥 FE, UI, Fix

#79 [FE] pr 리뷰 반영
  fe/src/components/Atoms/Dropdown/DropdownPanels/index.tsx
  fe/src/components/Atoms/Dropdown/index.tsx
  fe/src/components/Molecules/FilterBar/index.tsx
  fe/src/components/Molecules/IssueList/index.tsx
  fe/src/components/Molecules/SideBar/SideBar.stories.tsx
  fe/src/components/Molecules/SideBar/index.tsx
  fe/src/components/types.ts
  fe/src/pages/AddIssue.tsx
  fe/src/pages/IssueDetail.tsx
Labels: 🖥 FE, Fix
